In [1]:
import pandas as pd

In [2]:
fert_df = pd.read_csv('Punjab 77th round.csv',index_col="Land owned (hectares)")
lit_df = pd.read_csv('Punjab 77th round.csv',index_col="HH size")

In [3]:
print(fert_df.head())

                           HHID  HH size  Socialgroup  Religion  \
Land owned (hectares)
0.126                  72500201        4            9         4
0.012                  72500202        5            3         1
0.429                  72500301        5            9         1
0.842                  72500302        8            9         4
13.649                 72500401        8            9         4

                       HHclassification  Land possessed (hectares)  \
Land owned (hectares)
0.126                                 7                      0.126
0.012                                 7                      0.012
0.429                                 6                      0.429
0.842                                 1                      0.842
13.649                                1                     13.649

                       Total monthly consumption expenditure (INR)  \
Land owned (hectares)
0.126                                                        13000
0.012                                                         9500
0.429                                                        22000
0.842                                                        18750
13.649                                                       28400

                       Monthly income from non farm activity (INR)  \
Land owned (hectares)
0.126                                                          0.0
0.012                                                          0.0
0.429                                                          0.0
0.842                                                          0.0
13.649                                                         0.0

                       Monthly income from wage employment (INR)  \
Land owned (hectares)
0.126                                                  10000.000
0.012                                                   6666.667
0.429                                                  40833.330
0.842                                                      0.000
13.649                                                     0.000

                       Monthly income from farming of animals (INR)  \
Land owned (hectares)
0.126                                                      6733.333
0.012                                                      3966.667
0.429                                                         0.000
0.842                                                     10966.670
13.649                                                     -300.000

                       Monthly income from crop production (INR)  \
Land owned (hectares)
0.126                                                   6393.750
0.012                                                      0.000
0.429                                                   7941.667
0.842                                                   6522.500
13.649                                                138274.300

                       Total Monthly Income (INR)  Frequency weight
Land owned (hectares)
0.126                                    23127.08              1664
0.012                                    10633.33              1664
0.429                                    48775.00              1152
0.842                                    17489.17              1152
13.649                                  137974.30               448

In [4]:
print(lit_df.head())

             HHID  Socialgroup  Religion  HHclassification  \
HH size
4        72500201            9         4                 7
5        72500202            3         1                 7
5        72500301            9         1                 6
8        72500302            9         4                 1
8        72500401            9         4                 1

         Land owned (hectares)  Land possessed (hectares)  \
HH size
4                        0.126                      0.126
5                        0.012                      0.012
5                        0.429                      0.429
8                        0.842                      0.842
8                       13.649                     13.649

         Total monthly consumption expenditure (INR)  \
HH size
4                                              13000
5                                               9500
5                                              22000
8                                              18750
8                                              28400

         Monthly income from non farm activity (INR)  \
HH size
4                                                0.0
5                                                0.0
5                                                0.0
8                                                0.0
8                                                0.0

         Monthly income from wage employment (INR)  \
HH size
4                                        10000.000
5                                         6666.667
5                                        40833.330
8                                            0.000
8                                            0.000

         Monthly income from farming of animals (INR)  \
HH size
4                                            6733.333
5                                            3966.667
5                                               0.000
8                                           10966.670
8                                            -300.000

         Monthly income from crop production (INR)  \
HH size
4                                         6393.750
5                                            0.000
5                                         7941.667
8                                         6522.500
8                                       138274.300

         Total Monthly Income (INR)  Frequency weight
HH size
4                          23127.08              1664
5                          10633.33              1664
5                          48775.00              1152
8                          17489.17              1152
8                         137974.30               448

In [5]:
merged_df = pd.merge(fert_df,lit_df, on="HHID", how ="inner")#inner is intersection, outer is union, left and right try

In [6]:
print(merged_df.head())

       HHID  HH size  Socialgroup_x  Religion_x  HHclassification_x  \
0  72500201        4              9           4                   7
1  72500202        5              3           1                   7
2  72500301        5              9           1                   6
3  72500302        8              9           4                   1
4  72500401        8              9           4                   1

   Land possessed (hectares)_x  Total monthly consumption expenditure (INR)_x  \
0                        0.126                                          13000
1                        0.012                                           9500
2                        0.429                                          22000
3                        0.842                                          18750
4                       13.649                                          28400

   Monthly income from non farm activity (INR)_x  \
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0

   Monthly income from wage employment (INR)_x  \
0                                    10000.000
1                                     6666.667
2                                    40833.330
3                                        0.000
4                                        0.000

   Monthly income from farming of animals (INR)_x  ...  HHclassification_y  \
0                                        6733.333  ...                   7
1                                        3966.667  ...                   7
2                                           0.000  ...                   6
3                                       10966.670  ...                   1
4                                        -300.000  ...                   1

   Land owned (hectares)  Land possessed (hectares)_y  \
0                  0.126                        0.126
1                  0.012                        0.012
2                  0.429                        0.429
3                  0.842                        0.842
4                 13.649                       13.649

   Total monthly consumption expenditure (INR)_y  \
0                                          13000
1                                           9500
2                                          22000
3                                          18750
4                                          28400

   Monthly income from non farm activity (INR)_y  \
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0

   Monthly income from wage employment (INR)_y  \
0                                    10000.000
1                                     6666.667
2                                    40833.330
3                                        0.000
4                                        0.000

   Monthly income from farming of animals (INR)_y  \
0                                        6733.333
1                                        3966.667
2                                           0.000
3                                       10966.670
4                                        -300.000

   Monthly income from crop production (INR)_y  Total Monthly Income (INR)_y  \
0                                     6393.750                      23127.08
1                                        0.000                      10633.33
2                                     7941.667                      48775.00
3                                     6522.500                      17489.17
4                                   138274.300                     137974.30

   Frequency weight_y
0                1664
1                1664
2                1152
3                1152
4                 448

[5 rows x 25 columns]

In [7]:
print(merged_df)

         HHID  HH size  Socialgroup_x  Religion_x  HHclassification_x  \
0    72500201        4              9           4                   7
1    72500202        5              3           1                   7
2    72500301        5              9           1                   6
3    72500302        8              9           4                   1
4    72500401        8              9           4                   1
..        ...      ...            ...         ...                 ...
880  72979302        4              9           4                   1
881  72979401        5              9           4                   1
882  72979402        6              9           4                   1
883  72979501        5              9           4                   1
884  72979502        7              9           4                   1

     Land possessed (hectares)_x  \
0                          0.126
1                          0.012
2                          0.429
3                          0.842
4                         13.649
..                           ...
880                        0.931
881                        1.438
882                        1.660
883                        7.088
884                        4.941

     Total monthly consumption expenditure (INR)_x  \
0                                            13000
1                                             9500
2                                            22000
3                                            18750
4                                            28400
..                                             ...
880                                          12100
881                                          18767
882                                          35750
883                                          28417
884                                          29333

     Monthly income from non farm activity (INR)_x  \
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0
..                                             ...
880                                            0.0
881                                            0.0
882                                            0.0
883                                            0.0
884                                            0.0

     Monthly income from wage employment (INR)_x  \
0                                      10000.000
1                                       6666.667
2                                      40833.330
3                                          0.000
4                                          0.000
..                                           ...
880                                        0.000
881                                    16000.000
882                                        0.000
883                                        0.000
884                                     3450.000

     Monthly income from farming of animals (INR)_x  ...  HHclassification_y  \
0                                          6733.333  ...                   7
1                                          3966.667  ...                   7
2                                             0.000  ...                   6
3                                         10966.670  ...                   1
4                                          -300.000  ...                   1
..                                              ...  ...                 ...
880                                        2683.333  ...                   1
881                                        1440.000  ...                   1
882                                       -1666.667  ...                   1
883                                        4406.667  ...                   1
884                                       13050.000  ...                   1

     Land owned (hectares)  Land possessed (hectares)_y  \
0                    0.126                        0.126
1                    0.012                        0.012
2                    0.429                        0.429
3                    0.842                        0.842
4                   13.649                       13.649
..                     ...                          ...
880                  0.931                        0.931
881                  1.438                        1.438
882                  1.660                        1.660
883                  1.013                        7.088
884                  4.131                        4.941

     Total monthly consumption expenditure (INR)_y  \
0                                            13000
1                                             9500
2                                            22000
3                                            18750
4                                            28400
..                                             ...
880                                          12100
881                                          18767
882                                          35750
883                                          28417
884                                          29333

     Monthly income from non farm activity (INR)_y  \
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0
..                                             ...
880                                            0.0
881                                            0.0
882                                            0.0
883                                            0.0
884                                            0.0

     Monthly income from wage employment (INR)_y  \
0                                      10000.000
1                                       6666.667
2                                      40833.330
3                                          0.000
4                                          0.000
..                                           ...
880                                        0.000
881                                    16000.000
882                                        0.000
883                                        0.000
884                                     3450.000

     Monthly income from farming of animals (INR)_y  \
0                                          6733.333
1                                          3966.667
2                                             0.000
3                                         10966.670
4                                          -300.000
..                                              ...
880                                        2683.333
881                                        1440.000
882                                       -1666.667
883                                        4406.667
884                                       13050.000

     Monthly income from crop production (INR)_y  \
0                                       6393.750
1                                          0.000
2                                       7941.667
3                                       6522.500
4                                     138274.300
..                                           ...
880                                     9386.500
881                                    17182.420
882                                    17004.000
883                                    19373.580
884                                    71569.660

     Total Monthly Income (INR)_y  Frequency weight_y
0                        23127.08                1664
1                        10633.33                1664
2                        48775.00                1152
3                        17489.17                1152
4                       137974.30                 448
..                            ...                 ...
880                      12069.83                 489
881                      34622.41                1173
882                      15337.33                1173
883                      23780.25                2053
884                      88069.66                2053

[885 rows x 25 columns]

In [8]:
total_female_df = merged_df[["Land owned (hectares)", "HH size"]]

In [9]:
print(total_female_df.head())

   Land owned (hectares)  HH size
0                  0.126        4
1                  0.012        5
2                  0.429        5
3                  0.842        8
4                 13.649        8

In [10]:
total_female_corr = total_female_df["HH size"].corr(total_female_df["Land owned (hectares)"])# a corr b and b corr a are equal
print(total_female_corr)

0.13849295110449858