In [18]:
import pandas as pd

In [19]:
fert_df = pd.read_csv('Punjab 77th round.csv',index_col="Land possessed (hectares)")
lit_df = pd.read_csv('Punjab 77th round.csv',index_col="Monthly income from crop production (INR)")

In [20]:
print(fert_df.head())

                               HHID  HH size  Socialgroup  Religion  \
Land possessed (hectares)
0.126                      72500201        4            9         4
0.012                      72500202        5            3         1
0.429                      72500301        5            9         1
0.842                      72500302        8            9         4
13.649                     72500401        8            9         4

                           HHclassification  Land owned (hectares)  \
Land possessed (hectares)
0.126                                     7                  0.126
0.012                                     7                  0.012
0.429                                     6                  0.429
0.842                                     1                  0.842
13.649                                    1                 13.649

                           Total monthly consumption expenditure (INR)  \
Land possessed (hectares)
0.126                                                            13000
0.012                                                             9500
0.429                                                            22000
0.842                                                            18750
13.649                                                           28400

                           Monthly income from non farm activity (INR)  \
Land possessed (hectares)
0.126                                                              0.0
0.012                                                              0.0
0.429                                                              0.0
0.842                                                              0.0
13.649                                                             0.0

                           Monthly income from wage employment (INR)  \
Land possessed (hectares)
0.126                                                      10000.000
0.012                                                       6666.667
0.429                                                      40833.330
0.842                                                          0.000
13.649                                                         0.000

                           Monthly income from farming of animals (INR)  \
Land possessed (hectares)
0.126                                                          6733.333
0.012                                                          3966.667
0.429                                                             0.000
0.842                                                         10966.670
13.649                                                         -300.000

                           Monthly income from crop production (INR)  \
Land possessed (hectares)
0.126                                                       6393.750
0.012                                                          0.000
0.429                                                       7941.667
0.842                                                       6522.500
13.649                                                    138274.300

                           Total Monthly Income (INR)  Frequency weight
Land possessed (hectares)
0.126                                        23127.08              1664
0.012                                        10633.33              1664
0.429                                        48775.00              1152
0.842                                        17489.17              1152
13.649                                      137974.30               448

In [21]:
print(lit_df.head())

                                               HHID  HH size  Socialgroup  \
Monthly income from crop production (INR)
6393.750                                   72500201        4            9
0.000                                      72500202        5            3
7941.667                                   72500301        5            9
6522.500                                   72500302        8            9
138274.300                                 72500401        8            9

                                           Religion  HHclassification  \
Monthly income from crop production (INR)
6393.750                                          4                 7
0.000                                             1                 7
7941.667                                          1                 6
6522.500                                          4                 1
138274.300                                        4                 1

                                           Land owned (hectares)  \
Monthly income from crop production (INR)
6393.750                                                   0.126
0.000                                                      0.012
7941.667                                                   0.429
6522.500                                                   0.842
138274.300                                                13.649

                                           Land possessed (hectares)  \
Monthly income from crop production (INR)
6393.750                                                       0.126
0.000                                                          0.012
7941.667                                                       0.429
6522.500                                                       0.842
138274.300                                                    13.649

                                           Total monthly consumption expenditure (INR)  \
Monthly income from crop production (INR)
6393.750                                                                         13000
0.000                                                                             9500
7941.667                                                                         22000
6522.500                                                                         18750
138274.300                                                                       28400

                                           Monthly income from non farm activity (INR)  \
Monthly income from crop production (INR)
6393.750                                                                           0.0
0.000                                                                              0.0
7941.667                                                                           0.0
6522.500                                                                           0.0
138274.300                                                                         0.0

                                           Monthly income from wage employment (INR)  \
Monthly income from crop production (INR)
6393.750                                                                   10000.000
0.000                                                                       6666.667
7941.667                                                                   40833.330
6522.500                                                                       0.000
138274.300                                                                     0.000

                                           Monthly income from farming of animals (INR)  \
Monthly income from crop production (INR)
6393.750                                                                       6733.333
0.000                                                                          3966.667
7941.667                                                                          0.000
6522.500                                                                      10966.670
138274.300                                                                     -300.000

                                           Total Monthly Income (INR)  \
Monthly income from crop production (INR)
6393.750                                                     23127.08
0.000                                                        10633.33
7941.667                                                     48775.00
6522.500                                                     17489.17
138274.300                                                  137974.30

                                           Frequency weight
Monthly income from crop production (INR)
6393.750                                               1664
0.000                                                  1664
7941.667                                               1152
6522.500                                               1152
138274.300                                              448

In [22]:
merged_df = pd.merge(fert_df,lit_df, on="HHID", how ="inner")#inner is intersection, outer is union, left and right try

In [23]:
print(merged_df.head())

       HHID  HH size_x  Socialgroup_x  Religion_x  HHclassification_x  \
0  72500201          4              9           4                   7
1  72500202          5              3           1                   7
2  72500301          5              9           1                   6
3  72500302          8              9           4                   1
4  72500401          8              9           4                   1

   Land owned (hectares)_x  Total monthly consumption expenditure (INR)_x  \
0                    0.126                                          13000
1                    0.012                                           9500
2                    0.429                                          22000
3                    0.842                                          18750
4                   13.649                                          28400

   Monthly income from non farm activity (INR)_x  \
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0

   Monthly income from wage employment (INR)_x  \
0                                    10000.000
1                                     6666.667
2                                    40833.330
3                                        0.000
4                                        0.000

   Monthly income from farming of animals (INR)_x  ...  Religion_y  \
0                                        6733.333  ...           4
1                                        3966.667  ...           1
2                                           0.000  ...           1
3                                       10966.670  ...           4
4                                        -300.000  ...           4

   HHclassification_y  Land owned (hectares)_y  Land possessed (hectares)  \
0                   7                    0.126                      0.126
1                   7                    0.012                      0.012
2                   6                    0.429                      0.429
3                   1                    0.842                      0.842
4                   1                   13.649                     13.649

   Total monthly consumption expenditure (INR)_y  \
0                                          13000
1                                           9500
2                                          22000
3                                          18750
4                                          28400

   Monthly income from non farm activity (INR)_y  \
0                                            0.0
1                                            0.0
2                                            0.0
3                                            0.0
4                                            0.0

   Monthly income from wage employment (INR)_y  \
0                                    10000.000
1                                     6666.667
2                                    40833.330
3                                        0.000
4                                        0.000

   Monthly income from farming of animals (INR)_y  \
0                                        6733.333
1                                        3966.667
2                                           0.000
3                                       10966.670
4                                        -300.000

   Total Monthly Income (INR)_y  Frequency weight_y
0                      23127.08                1664
1                      10633.33                1664
2                      48775.00                1152
3                      17489.17                1152
4                     137974.30                 448

[5 rows x 25 columns]

In [24]:
print(merged_df)

         HHID  HH size_x  Socialgroup_x  Religion_x  HHclassification_x  \
0    72500201          4              9           4                   7
1    72500202          5              3           1                   7
2    72500301          5              9           1                   6
3    72500302          8              9           4                   1
4    72500401          8              9           4                   1
..        ...        ...            ...         ...                 ...
880  72979302          4              9           4                   1
881  72979401          5              9           4                   1
882  72979402          6              9           4                   1
883  72979501          5              9           4                   1
884  72979502          7              9           4                   1

     Land owned (hectares)_x  Total monthly consumption expenditure (INR)_x  \
0                      0.126                                          13000
1                      0.012                                           9500
2                      0.429                                          22000
3                      0.842                                          18750
4                     13.649                                          28400
..                       ...                                            ...
880                    0.931                                          12100
881                    1.438                                          18767
882                    1.660                                          35750
883                    1.013                                          28417
884                    4.131                                          29333

     Monthly income from non farm activity (INR)_x  \
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0
..                                             ...
880                                            0.0
881                                            0.0
882                                            0.0
883                                            0.0
884                                            0.0

     Monthly income from wage employment (INR)_x  \
0                                      10000.000
1                                       6666.667
2                                      40833.330
3                                          0.000
4                                          0.000
..                                           ...
880                                        0.000
881                                    16000.000
882                                        0.000
883                                        0.000
884                                     3450.000

     Monthly income from farming of animals (INR)_x  ...  Religion_y  \
0                                          6733.333  ...           4
1                                          3966.667  ...           1
2                                             0.000  ...           1
3                                         10966.670  ...           4
4                                          -300.000  ...           4
..                                              ...  ...         ...
880                                        2683.333  ...           4
881                                        1440.000  ...           4
882                                       -1666.667  ...           4
883                                        4406.667  ...           4
884                                       13050.000  ...           4

     HHclassification_y  Land owned (hectares)_y  Land possessed (hectares)  \
0                     7                    0.126                      0.126
1                     7                    0.012                      0.012
2                     6                    0.429                      0.429
3                     1                    0.842                      0.842
4                     1                   13.649                     13.649
..                  ...                      ...                        ...
880                   1                    0.931                      0.931
881                   1                    1.438                      1.438
882                   1                    1.660                      1.660
883                   1                    1.013                      7.088
884                   1                    4.131                      4.941

     Total monthly consumption expenditure (INR)_y  \
0                                            13000
1                                             9500
2                                            22000
3                                            18750
4                                            28400
..                                             ...
880                                          12100
881                                          18767
882                                          35750
883                                          28417
884                                          29333

     Monthly income from non farm activity (INR)_y  \
0                                              0.0
1                                              0.0
2                                              0.0
3                                              0.0
4                                              0.0
..                                             ...
880                                            0.0
881                                            0.0
882                                            0.0
883                                            0.0
884                                            0.0

     Monthly income from wage employment (INR)_y  \
0                                      10000.000
1                                       6666.667
2                                      40833.330
3                                          0.000
4                                          0.000
..                                           ...
880                                        0.000
881                                    16000.000
882                                        0.000
883                                        0.000
884                                     3450.000

     Monthly income from farming of animals (INR)_y  \
0                                          6733.333
1                                          3966.667
2                                             0.000
3                                         10966.670
4                                          -300.000
..                                              ...
880                                        2683.333
881                                        1440.000
882                                       -1666.667
883                                        4406.667
884                                       13050.000

     Total Monthly Income (INR)_y  Frequency weight_y
0                        23127.08                1664
1                        10633.33                1664
2                        48775.00                1152
3                        17489.17                1152
4                       137974.30                 448
..                            ...                 ...
880                      12069.83                 489
881                      34622.41                1173
882                      15337.33                1173
883                      23780.25                2053
884                      88069.66                2053

[885 rows x 25 columns]

In [25]:
total_female_df = merged_df[["Land possessed (hectares)", "Monthly income from crop production (INR)"]]

In [26]:
print(total_female_df.head())

   Land possessed (hectares)  Monthly income from crop production (INR)
0                      0.126                                   6393.750
1                      0.012                                      0.000
2                      0.429                                   7941.667
3                      0.842                                   6522.500
4                     13.649                                 138274.300

In [27]:
total_female_corr = total_female_df["Land possessed (hectares)"].corr(total_female_df["Monthly income from crop production (INR)"])
print(total_female_corr)

0.7229134427092724